#ifndef __NBL_THIS_EXAMPLE_RENDER_VARIANT_ENUMS_HLSL_INCLUDED__
#define __NBL_THIS_EXAMPLE_RENDER_VARIANT_ENUMS_HLSL_INCLUDED__

enum E_LIGHT_GEOMETRY : uint8_t
{
	ELG_SPHERE,
	ELG_TRIANGLE,
	ELG_RECTANGLE,
	ELG_COUNT
};

enum E_POLYGON_METHOD : uint8_t
{
	EPM_AREA,
	EPM_SOLID_ANGLE,
	EPM_PROJECTED_SOLID_ANGLE,
	EPM_COUNT
};

#endif
