#ifndef _NBL_THIS_EXAMPLE_RENDER_VARIANT_ENUMS_HLSL_INCLUDED_
#define _NBL_THIS_EXAMPLE_RENDER_VARIANT_ENUMS_HLSL_INCLUDED_

#ifndef __HLSL_VERSION
enum E_LIGHT_GEOMETRY : uint8_t
#else
enum E_LIGHT_GEOMETRY
#endif
{
	ELG_SPHERE,
	ELG_TRIANGLE,
	ELG_RECTANGLE,
	ELG_COUNT
};

#ifndef __HLSL_VERSION
enum E_POLYGON_METHOD : uint8_t
#else
enum E_POLYGON_METHOD
#endif
{
	EPM_AREA,
	EPM_SOLID_ANGLE,
	EPM_PROJECTED_SOLID_ANGLE,
	EPM_COUNT
};

#endif
