macro(PT_APPEND_SPIRV_RULE)
	set(options)
	set(oneValueArgs VAR INPUT KEY)
	set(multiValueArgs COMPILE_OPTIONS)
	cmake_parse_arguments(PT_RULE "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
	if(PT_RULE_INPUT STREQUAL "" OR PT_RULE_KEY STREQUAL "")
		message(FATAL_ERROR "PT_APPEND_SPIRV_RULE requires INPUT and KEY")
	endif()
	set(PT_RULE_JSON "{\"INPUT\":\"${PT_RULE_INPUT}\",\"KEY\":\"${PT_RULE_KEY}\"")
	if(PT_RULE_COMPILE_OPTIONS)
		set(PT_RULE_COMPILE_OPTIONS_JSON "")
		foreach(PT_RULE_COMPILE_OPTION IN LISTS PT_RULE_COMPILE_OPTIONS)
			string(APPEND PT_RULE_COMPILE_OPTIONS_JSON "\"${PT_RULE_COMPILE_OPTION}\",")
		endforeach()
		string(REGEX REPLACE ",$" "" PT_RULE_COMPILE_OPTIONS_JSON "${PT_RULE_COMPILE_OPTIONS_JSON}")
		string(APPEND PT_RULE_JSON ",\"COMPILE_OPTIONS\":[${PT_RULE_COMPILE_OPTIONS_JSON}]")
	endif()
	string(APPEND PT_RULE_JSON "}")
	list(APPEND ${PT_RULE_VAR} "${PT_RULE_JSON}")
endmacro()

macro(PT_FINALIZE_JSON_PAYLOAD)
	set(oneValueArgs INOUT)
	cmake_parse_arguments(PT_PAYLOAD "" "${oneValueArgs}" "" ${ARGN})
	if(PT_PAYLOAD_INOUT STREQUAL "")
		message(FATAL_ERROR "PT_FINALIZE_JSON_PAYLOAD requires INOUT")
	endif()
	string(JOIN ",\n" PT_RULES_BODY ${${PT_PAYLOAD_INOUT}})
	set(PT_PAYLOAD_TEMPLATE [=[
[
@PT_RULES_BODY@
]
]=])
	string(CONFIGURE "${PT_PAYLOAD_TEMPLATE}" ${PT_PAYLOAD_INOUT} @ONLY)
endmacro()
