#include "common.hlsl"

#include "nbl/examples/common/KeyedQuantizedSequence.hlsl"


using namespace nbl;
using namespace nbl::hlsl;
using namespace nbl::this_example;
using namespace nbl::hlsl::path_tracing;

[[vk::push_constant]] SBeautyPushConstants pc;

struct SSpectralType
{
    inline void clear()
    {
        transparency = weight;
        aovThroughput = promote<float16_t3>(weight);
        color = normal = albedo = float16_t3(0,0,0);
        // TODO: motion
    }

    // transparent (anyhit) could be emissive so needs to add its emission
    float16_t3 color;
    // AoVs are handled as "special emission", basically the contribution of albedo is same as the material illuminated in a White Furnace
    // so for transparent (anyhit) to impart its albedo or normal into the AoV it can add it same way it would add any color emission
    float16_t3 albedo;
    // One would think that normals can't be blended, but yes they can! Just make sure you weigh then using the Luma of the RGB aovThroughput.
    // Here's the problem with dealing with reflections & refractions, the reflection of a wall with an X- normal in the X+ window should have an apparent X+ normal.
    // This means that one would need to track the surfaces through which we reflect in a stack along the path, eg:
    // `originalNormal - 2 dot(originalNormal, reflectorNormal) * reflectorNormal == (Identity - 2 outerProductMatrix(reflectorNormal)) originalNormal`
    // To follow through 2 or more reflections we'd need to multiply these 3x3 matrices together along the ray like so
    // `(I - 2 n_0 n_0^T) (I - 2 n_1 n_1^T) = I + 4 n_0 (n_0^T n_1) n_1^T - 2 (n_0 n_0^T + n_1 n_1^T)`
    // Theoretically because every series of reflections is just one reflection and a rotation, it could be possible to store this in 3 floats, due to the properties of SO(3)
    // "The orthogonal group, consisting of all proper and improper rotations, is generated by reflections. Every proper rotation is the composition of two reflections, a special case of the Cartan–Dieudonné theorem."
    // I'm not sure how we could extend that for refractions but probably a similar form is possible  - virtual object corresponding under transmission to what's seen under refraction.
    // The question is.. is it worth it? Do er really need objects warped by in a labyrynth of wonky mirrors to have warped normals? Or a ceiling reflected in a choppy swimming pool to inherit the pool's wave normals ?
    // NO because this is an input to a denoiser to stop it blurring lighting across surfaces oriented in different directions! Doesn't matter what the reflection and refraction normals are as long as they're consistent.
    // For the example of a flat building wall reflected in a wavy but smooth reflector, that would actually be a massive self-own and leave behind a lot of noise!
    float16_t3 normal;
    // TODO: motion (RG vector to past location, B or BA as a measure of spread, e.g. spherical gaussian, direction and its variance, Polar Harmonics - Laplace on a Circle)
};
// variables that multiply together
struct SThroughputs
{
    inline void clear(const float16_t weight)
    {
        aovThroughput = throughput = promote<float16_t3>(weight);
        transparency = weight;
    }

    // transparent (anyhit) could be emissive so needs to add its emission
    float16_t3 throughput;
    // RGB transparency of smooth reflections and refractions, used for modulating albedo and most AOVs
    float16_t3 aovThroughput;
    // Motion is special because Real Time defines it as a mapping of where current pixel was last frame.
    // True motion output would require us to implement differentiable rendering and formulate motion as an integral of `Throughput dScreenPos/dTime` which is super tricky because:
    // - A turning mirror imparts motion on the reflection of a static object
    // - whats the motion vector for a disoccluded part of a reflection? How to even know about a disocclusion/our reflection's motion vector reprojecting badly?
    // - its not generally a function, the current pixel could be in multiple places at in the last frame (think about the flow of the reflection of your face in a concave spoon) 
    // - Non-differentiability, hard edges of triangles and Breps
    // - lighting imparts is own motion vectors, e.g. shadows move across static surfaces
    // - how to weigh contributions? luma of RGB effect? inidividually, etc.
    // TL;DR you can't just blend motions and get something useful (even less than normals), only directly tranmissive paths should be allowed to accumulate their motion vectors (easy to calculate)
    // as we pass through surfaces we need to know how much of the outgoing ray distribution is focused around the directly transmissive direction. This can modulate both our masking and motion vectors.
    // Albeit for smooth but refractive surfaces we could experiment with accepting transparent masking even though ray direction won't match in a simple Photoshop composting,
    // but would you rather have an opaque swimming pool, round glass vase, or water droplet OR composted with no refraction? But then we'd need a motion throughput and track some more metadata.
    float16_t transparency;
};

struct[raypayload] BeautyPayload
{
    // opacity russian roulette requires this for Discrete Probability Sampling
    float xi;
#if 0
    inline void init(const float16_t sampleWeight)
    {
        throughput = promote<float16_t3>(sampleWeight);
        accumulation.clear(sampleWeight);
        otherTechniqueHeuristic = 0.f;
    }

    // TODO: investigate reading from scramble texture instead
    scramble_state_t dimensionScramble : read(caller,anyhit,closesthit,miss) : write(caller);
    // all shading gets done in raygen (raygen does shading via callables)
    // anyhit can mix in its own stuff during thindielectric and opaque trace
#endif
    // Material evaluation and stochastic opacity in anyhit shader requires we this whole struct in the payload
    SSpectralType accumulation : read(caller,anyhit) : write(caller,anyhit);
    // transparent (anyhit) can perform Russian Roulette to accept or reject a hit
    SThroughputs throughput : read(caller,anyhit) : write(caller,anyhit);
#if 0
    // world space normal
    float16_t3 normalAtOrigin : read(caller,anyhit) : write(caller,closesthit,anyhit);
    // TODO up for debate whether to make this a full float
    // Raygen or callable sets it before shooting another ray, gets read when ray comes back with an intersection
    // MIS needs to be applied on transparent emitters, so anyhit reads
    float32_t otherTechniqueHeuristic : read(caller,anyhit) : write(caller);
#endif
    // TODO: options for killing specular after diffuse paths
};

[shader("raygeneration")]
void raygen()
{
    const uint16_t3 launchID = uint16_t3(spirv::LaunchIdKHR);

    // Take n samples per frame
    // TODO: establish min/max - adaptive sampling
    uint16_t samplesThisFrame = uint16_t(pc.maxSppPerDispatch);
    SPixelSamplingInfo samplingInfo = advanceSampleCount(launchID,samplesThisFrame,uint16_t(pc.sensorDynamics.keepAccumulating));
    // took 64k-1 spp
    if (samplingInfo.rcpNewSampleCount==0.f)
        return;
    // weight for non RWMC contribution
    const float16_t newSamplesOverTotal = float16_t(float32_t(samplesThisFrame)*samplingInfo.rcpNewSampleCount);
    
    // get our NDC coordinates
    const float32_t2 pixelSizeNDC = promote<float32_t2>(2.f) / float32_t2(spirv::LaunchSizeKHR.xy);
    const float32_t2 NDC = float32_t2(launchID.xy) * pixelSizeNDC - promote<float32_t2>(1.f);

    // make the accumulation compute the average of current samples
    SSpectralType accumulation;
    accumulation.clear(float16_t(1)/float16_t(samplesThisFrame));

    // primary visibility ray
    {
        const float16_t2 randVec = float16_t2(samplingInfo.randgen(0u,samplingInfo.firstSample).xy);
        const SRay ray = SRay::create(pc.sensorDynamics,pixelSizeNDC,NDC,randVec);
    }
    // trace further paths
    [[loop]] for (uint16_t depth=1; depth!=gSensor.lastPathDepth; depth++)
    {
        if (depth>gSensor.lastNoRussianRouletteDepth &&)
        {
//            accumulation = accumulation*rcpPdf;
            break;
        }

        //
        spirv::traceRayKHR(gTLASes[0], spv::RayFlagsMaskNone, 0xff, 0u, 0u, 0u, ray.origin, ray.tMin, ray.direction, ray.tMax, payload);
    }

    // TODO:
    // - small payload

//    Accumulator<gRWMCCascades> beautyAcc;
//    beautyAcc.accumulate(launchID.xy,launchID.z,float32_t3(accumulation.color),samplingInfo.rcpNewSampleCount);
    // albedo
    Accumulator<ImageAccessor_gAlbedo> albedoAcc;
    albedoAcc.accumulate(launchID.xy,launchID.z,accumulation.albedo,newSamplesOverTotal);
    // normal
    Accumulator<ImageAccessor_gNormal> normalAcc;
    normalAcc.accumulate(launchID.xy,launchID.z,correctSNorm10WhenStoringToUnorm(accumulation.normal),newSamplesOverTotal);
    // TODO: motion
    // mask
    Accumulator<ImageAccessor_gMask> maskAcc;
    maskAcc.accumulate(launchID.xy,launchID.z,vector<float16_t,1>(accumulation.transparency),newSamplesOverTotal);
}

[shader("closesthit")]
void closesthit(inout BeautyPayload payload, in BuiltInTriangleIntersectionAttributes attribs)
{
}

// TODO: Anyhit transparency
// - russian roulette accept hit, means we bump throughput by rcpPdf when we chose to continue
// - reuse Z random variable coordinate from current closest hit

[shader("miss")]
void miss(inout BeautyPayload payload)
{
    // mark as a miss
}