#ifndef _PT_COMPUTE_TRIANGLE_PERSISTENT_INCLUDED_
#define _PT_COMPUTE_TRIANGLE_PERSISTENT_INCLUDED_

#define PT_VARIANT_USE_RWMC 0
#define PT_VARIANT_ENABLE_LINEAR 0
#define PT_VARIANT_ENABLE_PERSISTENT 1
#include "pt.compute.triangle.methods.shared.hlsl"

#endif
