#pragma once

#if !defined(PT_VARIANT_USE_RWMC) || !defined(PT_VARIANT_SCENE_KIND)
#error Missing path tracer variant compile options
#endif

#define PT_VARIANT_SCENE_SPHERE 0
#define PT_VARIANT_SCENE_RECTANGLE 2

#if PT_VARIANT_USE_RWMC
#define PATH_TRACER_VARIANT_USE_RWMC true
#else
#define PATH_TRACER_VARIANT_USE_RWMC false
#endif
#define PATH_TRACER_USE_RWMC PT_VARIANT_USE_RWMC

#include "compute.render.common.hlsl"
#if PT_VARIANT_SCENE_KIND == PT_VARIANT_SCENE_SPHERE
#define PATH_TRACER_VARIANT_GEOMETRY ELG_SPHERE
#define PATH_TRACER_VARIANT_POLYGON_METHOD EPM_SOLID_ANGLE
#define PATH_TRACER_VARIANT_ENTRYPOINT_POLYGON_METHOD PPM_SOLID_ANGLE
#define PATH_TRACER_ENTRYPOINT_POLYGON_METHOD PPM_SOLID_ANGLE
#include "scene_sphere_light.hlsl"
#elif PT_VARIANT_SCENE_KIND == PT_VARIANT_SCENE_RECTANGLE
#define PATH_TRACER_VARIANT_GEOMETRY ELG_RECTANGLE
#define PATH_TRACER_VARIANT_POLYGON_METHOD EPM_PROJECTED_SOLID_ANGLE
#define PATH_TRACER_VARIANT_ENTRYPOINT_POLYGON_METHOD PPM_APPROX_PROJECTED_SOLID_ANGLE
#define PATH_TRACER_ENTRYPOINT_POLYGON_METHOD PPM_APPROX_PROJECTED_SOLID_ANGLE
#include "scene_rectangle_light.hlsl"
#else
#error Unsupported PT_VARIANT_SCENE_KIND
#endif
#include "nbl/this_example/render_variant_config.hlsl"
#include "compute_render_scene_impl.hlsl"

#include "compute.render.persistent.entrypoints.hlsl"
#if PT_VARIANT_SCENE_KIND == PT_VARIANT_SCENE_RECTANGLE
#define PATH_TRACER_ENTRYPOINT_NAME mainPersistentArea
#define PATH_TRACER_ENTRYPOINT_POLYGON_METHOD PPM_AREA
#include "compute.render.persistent.entrypoints.hlsl"

#define PATH_TRACER_ENTRYPOINT_NAME mainPersistentSolidAngle
#define PATH_TRACER_ENTRYPOINT_POLYGON_METHOD PPM_SOLID_ANGLE
#include "compute.render.persistent.entrypoints.hlsl"
#endif

#undef PATH_TRACER_ENTRYPOINT_POLYGON_METHOD
#undef PATH_TRACER_USE_RWMC
#undef PATH_TRACER_VARIANT_ENTRYPOINT_POLYGON_METHOD
#undef PATH_TRACER_VARIANT_POLYGON_METHOD
#undef PATH_TRACER_VARIANT_GEOMETRY
#undef PATH_TRACER_VARIANT_USE_RWMC
