#pragma once

#if !defined(PT_VARIANT_USE_RWMC) || !defined(PT_VARIANT_SCENE_KIND) || !defined(PT_VARIANT_ENTRYPOINT_KIND)
#error Missing path tracer variant compile options
#endif

#define PT_VARIANT_SCENE_SPHERE 0
#define PT_VARIANT_SCENE_RECTANGLE 2
#define PT_VARIANT_ENTRYPOINT_COMBINED 0
#define PT_VARIANT_ENTRYPOINT_LINEAR 1
#define PT_VARIANT_ENTRYPOINT_PERSISTENT 2

#define PATH_TRACER_USE_RWMC PT_VARIANT_USE_RWMC
#if PT_VARIANT_ENTRYPOINT_KIND == PT_VARIANT_ENTRYPOINT_COMBINED
#define PATH_TRACER_ENABLE_LINEAR 1
#define PATH_TRACER_ENABLE_PERSISTENT 1
#elif PT_VARIANT_ENTRYPOINT_KIND == PT_VARIANT_ENTRYPOINT_LINEAR
#define PATH_TRACER_ENABLE_LINEAR 1
#define PATH_TRACER_ENABLE_PERSISTENT 0
#elif PT_VARIANT_ENTRYPOINT_KIND == PT_VARIANT_ENTRYPOINT_PERSISTENT
#define PATH_TRACER_ENABLE_LINEAR 0
#define PATH_TRACER_ENABLE_PERSISTENT 1
#else
#error Unsupported PT_VARIANT_ENTRYPOINT_KIND
#endif

#include "compute.render.common.hlsl"
#if PT_VARIANT_SCENE_KIND == PT_VARIANT_SCENE_SPHERE
#define PT_VARIANT_POLYGON_METHOD PPM_SOLID_ANGLE
#include "scene_sphere_light.hlsl"
#elif PT_VARIANT_SCENE_KIND == PT_VARIANT_SCENE_RECTANGLE
#define PT_VARIANT_POLYGON_METHOD PPM_SOLID_ANGLE
#include "scene_rectangle_light.hlsl"
#else
#error Unsupported PT_VARIANT_SCENE_KIND
#endif
#include "compute_render_scene_impl.hlsl"

#if PT_VARIANT_ENTRYPOINT_KIND == PT_VARIANT_ENTRYPOINT_COMBINED
#define PATH_TRACER_ENTRYPOINT_POLYGON_METHOD PT_VARIANT_POLYGON_METHOD
#include "compute.render.linear.entrypoints.hlsl"
#define PATH_TRACER_ENTRYPOINT_POLYGON_METHOD PT_VARIANT_POLYGON_METHOD
#include "compute.render.persistent.entrypoints.hlsl"
#elif PT_VARIANT_ENTRYPOINT_KIND == PT_VARIANT_ENTRYPOINT_LINEAR
#define PATH_TRACER_ENTRYPOINT_POLYGON_METHOD PT_VARIANT_POLYGON_METHOD
#include "compute.render.linear.entrypoints.hlsl"
#else
#define PATH_TRACER_ENTRYPOINT_POLYGON_METHOD PT_VARIANT_POLYGON_METHOD
#include "compute.render.persistent.entrypoints.hlsl"
#endif

#undef PT_VARIANT_POLYGON_METHOD
