(() => {
	"use strict";

	const HINTS = {
		errorThreshold: "Per-channel relative tolerance used when comparing render and reference EXR values. If an RGB channel differs by more than this threshold, the pixel is counted as bad.",
		generated: "Local timestamp when this summary was produced by the path tracer executable.",
		ciStatus: "Overall validation status. It fails if any checked output exceeds its allowed bad-pixel budget or hits a processing error.",
		allowedBadPixels: "Maximum fraction of pixels that may be outside tolerance before an output is marked as failed. The concrete pixel budget is shown per output below.",
		scenes: "Number of scene and sensor render sessions included in this report.",
		miniSummary: "Scene-level pass, fail and not-checked totals for this report.",
		postprocessSummary: "Current state of report-visible path tracer postprocess outputs.",
		ldsHash: "BLAKE3 hash of the sampler sequence cache used by the run. A change here can explain render drift even if code did not change.",
		ldsStatus: "Whether the low discrepancy sequence cache file was created, changed, stayed identical, or was unavailable during this run.",
		badPixels: "Bad pixels are pixels where at least one RGB channel is outside the configured tolerance. The right side is the maximum allowed count for this image.",
		errorMetric: "First value is the bad-pixel percentage. Max is the largest absolute RGB channel error found in this output.",
		ssimMetric: "Denoised output is checked with structural similarity. The value is 1 - SSIM, so lower is better.",
		denoiserMode: "Current postprocess mode for output_denoised. No-op copy means denoiser integration is not enabled yet.",
		commitHash: "Nabla commit used by the executable that generated this report. The link opens the matching upstream commit when available.",
		commitDate: "Commit date recorded by git for the Nabla revision used in this run.",
		commitMessage: "Commit subject and body for the Nabla revision used in this run.",
		scenePath: "Scene file path recorded in the summary. Report payloads use paths relative to the report whenever possible.",
		sensor: "Sensor index rendered from the scene file.",
		outputTonemap: "Final tonemapped screenshot output. This is the primary render image used for visual review.",
		outputRwmcCascades: "Raw RWMC cascade export used to inspect the current resolver input and debug cascade content.",
		outputAlbedo: "Albedo AOV exported by the path tracer for denoising and material validation.",
		outputNormal: "Normal AOV exported by the path tracer for denoising and geometry validation.",
		outputDenoised: "Denoised output slot. It is currently a no-op copy of tonemap until the denoiser integration lands.",
		buildConfig: "Build configuration recorded by the path tracer executable that generated this report.",
		renderArtifact: "Download the rendered EXR artifact.",
		referenceArtifact: "Download the reference EXR copied into this report bundle.",
		differenceArtifact: "Download the generated EXR difference image.",
		missingOutput: "This output was recorded by the report but one side of the comparison is unavailable. Check the detail text to see whether the render, reference, or difference image is missing.",
		missingRender: "The reference exists, but this report has no unambiguous EXR produced by the current path tracer run for this output.",
		missingReference: "The current render may exist, but the checked-out reference set does not contain a matching reference EXR for this output.",
		machine: "Machine that generated this report, as recorded by the path tracer executable.",
		machineGpu: "GPU selected by the path tracer runtime for this report.",
		machineMemory: "Physical system memory reported by the operating system during the run.",
		previewButton: "Open this EXR in the built-in JavaScript preview.",
		copyPath: "Copy the report-relative artifact path. This stays valid after the report directory is moved.",
		reportBundle: "Report payload generated by the path tracer. Artifact links are report-relative so the directory is relocatable.",
		detailsButton: "Jump to the detailed table for this scene.",
		variantButton: "Switch the preview between render, reference and difference images.",
		overviewFilter: "Show every scene or only scenes with failing, missing, error or not-checked status.",
		overviewScene: "Rendered scene and sensor session. This uses the same display name as the EXR preview selector.",
		overviewDetails: "Open the detailed per-output table for this scene.",
		expandFailedOnly: "Open detail sections only for scenes that need attention and collapse passing scenes.",
		tonemapStep: "Primary tonemapped output used for visual review.",
		rwmcStep: "Resolved RWMC cascade output exported for debugging the current resolver path.",
		denoiseStep: "Denoised output state. It is currently a no-op copy until real denoising is integrated."
	};

	const state = {
		reportPath: "",
		summary: null,
		dataBaseUrl: null,
		overviewFilter: "all"
	};

	const nodes = {
		status: document.getElementById("reportStatus"),
		loadError: document.getElementById("loadError"),
		pipelineNotice: document.getElementById("pipelineNotice"),
		runCard: document.getElementById("runCard"),
		commitCard: document.getElementById("commitCard"),
		machineCard: document.getElementById("machineCard"),
		reportBundleCard: document.getElementById("reportBundleCard"),
		summaryCard: document.getElementById("summaryCard"),
		overviewCard: document.getElementById("overviewCard"),
		sceneDetails: document.getElementById("sceneDetails")
	};

	const viewer = window.DittExrPreview.createViewer({
		card: document.getElementById("exrViewerCard"),
		title: document.getElementById("exrViewerTitle"),
		status: document.getElementById("exrViewerStatus"),
		target: document.getElementById("exrPreview"),
		sceneSelect: document.getElementById("exrSceneSelect"),
		outputSelect: document.getElementById("exrOutputSelect"),
		variantTabs: document.getElementById("exrVariantTabs"),
		fitButton: document.getElementById("fitExrViewer"),
		oneToOneButton: document.getElementById("oneToOneExrViewer"),
		zoomOutButton: document.getElementById("zoomOutExrViewer"),
		zoomInButton: document.getElementById("zoomInExrViewer"),
		pixelInfo: document.getElementById("exrPixelInfo"),
		closeButton: document.getElementById("closeExrViewer")
	});

	function clear(node) {
		node.replaceChildren();
	}

	function append(parent, ...children) {
		for (const child of children) {
			if (child === null || child === undefined)
				continue;
			parent.appendChild(typeof child === "string" ? document.createTextNode(child) : child);
		}
		return parent;
	}

	function el(tag, options = {}, ...children) {
		const node = document.createElement(tag);
		if (options.className)
			node.className = options.className;
		if (options.text !== undefined)
			node.textContent = options.text;
		if (options.href)
			node.href = options.href;
		if (options.id)
			node.id = options.id;
		if (options.title)
			node.title = options.title;
		if (options.dataset)
			for (const [key,value] of Object.entries(options.dataset))
				node.dataset[key] = value;
		if (options.attrs)
			for (const [key,value] of Object.entries(options.attrs))
				node.setAttribute(key,value);
		append(node,...children);
		return node;
	}

	function hintLabel(label, hint) {
		return el("span",{ className: "hint-label", text: label, dataset: { hint }, attrs: { tabindex: "0" } });
	}

	function hintable(className, text, hint) {
		return el("div",{ className: className + " hintable", text, dataset: { hint }, attrs: { tabindex: "0" } });
	}

	function normalizeStatus(status) {
		return String(status || "not-checked").toLowerCase();
	}

	function statusClass(status) {
		const value = normalizeStatus(status);
		if (value === "passed")
			return "passed";
		if (value === "failed")
			return "failed";
		if (value === "error")
			return "error";
		if (value === "missing-reference" || value === "missing-render")
			return "missing";
		if (value === "not-checked")
			return "not-checked";
		return "unchecked";
	}

	function isProblemStatus(status) {
		return normalizeStatus(status) !== "passed";
	}

	function effectiveSceneStatus(scene) {
		const images = scene && scene.array ? scene.array : [];
		let checked = false;
		let unchecked = false;
		for (const image of images) {
			const status = normalizeStatus(image.status);
			if (status === "passed" || status === "failed")
				checked = true;
			if (status === "not-checked")
				unchecked = true;
			if (status === "failed" || status === "error" || status === "missing-render" || status === "missing-reference")
				return "failed";
		}

		const status = normalizeStatus(scene && scene.status);
		if (status === "failed" || status === "error" || status === "missing-render" || status === "missing-reference")
			return "failed";
		if (!checked && unchecked)
			return "not-checked";
		if (status === "not-checked")
			return "not-checked";
		return status === "passed" ? "passed":"not-checked";
	}

	function statusHint(status) {
		const value = normalizeStatus(status);
		if (value === "missing-render")
			return HINTS.missingRender;
		if (value === "missing-reference")
			return HINTS.missingReference;
		if (value === "not-checked")
			return "This output is present in the report but is intentionally not part of pass/fail validation.";
		if (value === "failed")
			return "This output failed validation or the scene has at least one failing output.";
		if (value === "passed")
			return "This output passed validation.";
		return "Report status recorded for this output.";
	}

	function sceneHasProblem(scene) {
		if (isProblemStatus(effectiveSceneStatus(scene)))
			return true;
		return (scene.array || []).some((image) => isProblemStatus(image.status));
	}

	function badge(status) {
		const value = normalizeStatus(status);
		return el("span",{ className: "badge " + statusClass(value), text: value, dataset: { hint: statusHint(value) }, attrs: { tabindex: "0" } });
	}

	function configBadge(config) {
		return el("span",{ className: "badge config", text: String(config || "unknown") });
	}

	function percent(value) {
		return (Number(value || 0)*100).toFixed(2).replace(/\.?0+$/,"") + "%";
	}

	function errorPercent(image) {
		const total = Number(image.total_pixels || 0);
		if (!total)
			return "0.0000%";
		return (100*Number(image.error_pixels || 0)/total).toFixed(4) + "%";
	}

	function isSsimMetric(image) {
		return image && (image.metric === "ssim" || image.ssim_difference !== undefined);
	}

	function suppressComparisonMetric(image) {
		const status = normalizeStatus(image && image.status);
		return status === "missing-render" || status === "missing-reference" || status === "not-checked" || status === "error";
	}

	function ssimDifferenceText(image) {
		const value = Number(image && image.ssim_difference);
		return Number.isFinite(value) ? value.toFixed(4) : "n/a";
	}

	function sci(value) {
		const number = Number(value || 0);
		return number.toExponential(3);
	}

	function formatBytes(value) {
		const number = Number(value || 0);
		if (!Number.isFinite(number) || number <= 0)
			return "unknown";
		const units = ["B","KiB","MiB","GiB","TiB"];
		let scaled = number;
		let unit = 0;
		while (scaled >= 1024 && unit + 1 < units.length) {
			scaled /= 1024;
			++unit;
		}
		return scaled.toFixed(unit ? 1 : 0).replace(/\.0$/,"") + " " + units[unit];
	}

	function installHintTooltip() {
		const tooltip = el("div",{ className: "hint-tooltip" });
		tooltip.hidden = true;
		document.body.appendChild(tooltip);
		let activeTarget = null;

		function rootRem() {
			return Number.parseFloat(getComputedStyle(document.documentElement).fontSize) || 16;
		}

		function rem(value) {
			return value*rootRem();
		}

		function lengthFromPixels(value) {
			return (value/rootRem()).toFixed(4).replace(/\.?0+$/,"") + "rem";
		}

		function position(target) {
			if (!target || tooltip.hidden)
				return;
			const rect = target.getBoundingClientRect();
			const margin = rem(0.625);
			const width = tooltip.offsetWidth || rem(20);
			const height = tooltip.offsetHeight || rem(3);
			let left = rect.left;
			let top = rect.bottom + margin;
			if (left + width > window.innerWidth - margin)
				left = window.innerWidth - width - margin;
			if (top + height > window.innerHeight - margin)
				top = rect.top - height - margin;
			tooltip.style.left = lengthFromPixels(Math.max(margin,left));
			tooltip.style.top = lengthFromPixels(Math.max(margin,top));
		}

		function show(target) {
			const hint = target && target.dataset ? target.dataset.hint : "";
			if (!hint)
				return;
			activeTarget = target;
			tooltip.textContent = hint;
			tooltip.hidden = false;
			position(target);
		}

		function hide(target) {
			if (target && activeTarget && target !== activeTarget)
				return;
			activeTarget = null;
			tooltip.hidden = true;
		}

		document.addEventListener("pointerover",(event) => {
			const target = event.target.closest("[data-hint]");
			if (target)
				show(target);
		});
		document.addEventListener("pointerout",(event) => {
			const target = event.target.closest("[data-hint]");
			if (target && !target.contains(event.relatedTarget))
				hide(target);
		});
		document.addEventListener("focusin",(event) => {
			const target = event.target.closest("[data-hint]");
			if (target)
				show(target);
		});
		document.addEventListener("focusout",(event) => {
			const target = event.target.closest("[data-hint]");
			if (target)
				hide(target);
		});
		window.addEventListener("scroll",() => position(activeTarget),true);
		window.addEventListener("resize",() => position(activeTarget));
	}

	installHintTooltip();

	function servedRootUrl() {
		return new URL("../",window.location.href);
	}

	function normalizeReportPath(path) {
		let value = String(path || "").trim();
		if (value.startsWith("#"))
			value = value.replace(/^#\/?/,"");
		try {
			value = decodeURIComponent(value);
		} catch (_) {
		}
		value = value.replace(/\\/g,"/").replace(/^\/+/,"").replace(/\/+$/,"");
		const parts = value.split("/").filter((part) => part && part !== ".");
		if (parts.some((part) => part === ".."))
			throw new Error("Report path must stay inside the served root.");
		return parts.join("/");
	}

	function reportBaseUrl(reportPath = state.reportPath) {
		if (!reportPath)
			return new URL("./",window.location.href);
		return new URL(reportPath.replace(/\/?$/,"/"),servedRootUrl());
	}

	function summaryUrl(reportPath = state.reportPath) {
		return new URL("summary.json",reportBaseUrl(reportPath)).href;
	}

	function artifactUrl(path) {
		if (!path)
			return "";
		return new URL(path,state.dataBaseUrl).href;
	}

	function artifactFilename(path) {
		return String(path || "").split("/").pop() || "artifact.exr";
	}

	function sceneAnchor(scene, fallbackIndex) {
		const name = String(scene.scene_name || scene.display_name || "scene").replace(/[^a-z0-9_-]+/gi,"-");
		return "scene-" + fallbackIndex + "-" + name;
	}

	async function loadSummary(reportPath) {
		const response = await fetch(summaryUrl(reportPath),{ cache: "no-store" });
		if (!response.ok)
			throw new Error(reportPath ? "No summary.json in " + reportPath : "No summary.json next to index.html. Open a local payload with a URL fragment like #/bin/out/my-run.");
		return await response.json();
	}

	function requestedReportPath() {
		return normalizeReportPath(window.location.hash);
	}

	function setReportHash(reportPath) {
		window.history.replaceState(null,"","#/" + encodeURI(reportPath));
	}

	function renderHeaderStatus() {
		nodes.status.replaceChildren(badge(state.summary.pass_status));
		if (state.summary.buildConfig)
			nodes.status.appendChild(configBadge(state.summary.buildConfig));
	}

	function runStat(label, hint, value, options = {}) {
		const stat = el("div",{ className: "stat" + (options.wide ? " wide" : "") });
		stat.appendChild(hintLabel(label,hint));
		stat.appendChild(el("strong",{ className: options.valueClass || "", text: value }));
		return stat;
	}

	function sceneStatusCounts(results) {
		const counts = {
			passed: 0,
			failed: 0,
			notChecked: 0
		};
		for (const scene of results || []) {
			const status = effectiveSceneStatus(scene);
			if (status === "passed")
				++counts.passed;
			else if (status === "not-checked")
				++counts.notChecked;
			else
				++counts.failed;
		}
		return counts;
	}

	function summaryChip(className, text) {
		return el("span",{ className: "summary-chip " + className, text });
	}

	function renderMiniSummary() {
		const counts = sceneStatusCounts(state.summary.results || []);
		return el("div",{ className: "mini-summary", dataset: { hint: HINTS.miniSummary }, attrs: { tabindex: "0" } },
			summaryChip("passed",String(counts.passed) + " passed"),
			summaryChip("failed",String(counts.failed) + " failed"),
			summaryChip("not-checked",String(counts.notChecked) + " not checked")
		);
	}

	function postprocessStep(label, stateClass, status, detail, hint) {
		return el("div",{ className: "postprocess-step " + stateClass, dataset: { hint }, attrs: { tabindex: "0" } },
			el("span",{ text: label }),
			el("strong",{ text: status }),
			el("small",{ text: detail })
		);
	}

	function renderPostprocessSummary() {
		const denoiser = state.summary.postprocess && state.summary.postprocess.denoiser;
		const denoiserMode = denoiser && denoiser.mode ? denoiser.mode : "not configured";
		const denoiserDetail = denoiserMode === "no-op-copy" ? "copy of tonemap" : denoiserMode;
		return el("div",{ className: "postprocess-summary", dataset: { hint: HINTS.postprocessSummary }, attrs: { tabindex: "0" } },
			el("div",{ className: "postprocess-title", text: "Postprocess" }),
			postprocessStep("Tonemap","ready","ready","rendered EXR",HINTS.tonemapStep),
			postprocessStep("RWMC resolve","ready","ready","cascade export",HINTS.rwmcStep),
			postprocessStep("Denoise",denoiserMode === "no-op-copy" ? "pending":"ready",denoiserMode,denoiserDetail,HINTS.denoiseStep)
		);
	}

	function renderPipelineNotice() {
		clear(nodes.pipelineNotice);
		const denoiser = state.summary.postprocess && state.summary.postprocess.denoiser;
		if (!denoiser) {
			nodes.pipelineNotice.hidden = true;
			return;
		}

		nodes.pipelineNotice.hidden = false;
		nodes.pipelineNotice.appendChild(el("div",{ className: "pipeline-toolbar-label", text: "Denoiser" }));
		nodes.pipelineNotice.appendChild(el("div",{ className: "pipeline-toolbar-mode", text: denoiser.mode || "unknown" }));
		nodes.pipelineNotice.appendChild(el("div",{ className: "pipeline-toolbar-message", text: denoiser.message || "Denoiser status is not available." }));
	}

	function ldsStatusText(cache) {
		const status = cache && cache.status ? cache.status : "not-configured";
		if (status === "did-not-change")
			return "LDS cache did not change";
		if (status === "created")
			return "LDS cache was created";
		if (status === "changed")
			return "LDS cache changed";
		if (status === "missing")
			return "LDS cache missing";
		return "LDS cache not configured";
	}

	function renderRunCard() {
		const summary = state.summary;
		const compare = summary.compare || {};
		const cache = summary.lowDiscrepancySequenceCache || {};
		clear(nodes.runCard);
		nodes.runCard.appendChild(el("h2",{ text: "Path Tracer Validation" }));
		nodes.runCard.appendChild(el("p",{ className: "ci-note" },
			hintLabel("Pixel error threshold",HINTS.errorThreshold),
			" allows output and reference RGB values to differ by up to ",
			el("strong",{ text: percent(compare.errorThreshold) }),
			" per channel."
		));
		nodes.runCard.appendChild(renderMiniSummary());
		nodes.runCard.appendChild(renderPostprocessSummary());

		const grid = el("div",{ className: "stat-grid" },
			runStat("Generated",HINTS.generated,summary.datetime || "unknown"),
			runStat("Build configuration",HINTS.buildConfig,summary.buildConfig || "unknown"),
			runStat("Validation status",HINTS.ciStatus,summary.pass_status || "unknown"),
			runStat("Allowed bad pixels",HINTS.allowedBadPixels,percent(compare.allowedErrorPixelRatio) + " of an image"),
			runStat("Scenes",HINTS.scenes,String(summary.num_of_tests || (summary.results || []).length)),
			runStat("SSIM threshold",HINTS.ssimMetric,String(compare.ssimErrorThreshold ?? "not configured")),
			runStat("Low discrepancy sequence cache hash",HINTS.ldsHash,cache.hash || "not available",{ wide: true, valueClass: "hash-value" }),
			runStat("LDS cache",HINTS.ldsStatus,ldsStatusText(cache),{ wide: true })
		);
		nodes.runCard.appendChild(grid);
	}

	function moduleCommit() {
		const modules = state.summary.build && state.summary.build.modules;
		return modules && modules.nabla ? modules.nabla : null;
	}

	function commitMessage(commit) {
		if (!commit)
			return "unknown";
		let message = commit.commitSubject || "unknown";
		if (commit.commitBody)
			message += "\n\n" + commit.commitBody;
		return message;
	}

	function artifactCounts() {
		const counts = {
			outputs: 0,
			render: 0,
			reference: 0,
			difference: 0,
			missingRender: 0,
			missingReference: 0
		};
		for (const scene of state.summary.results || []) {
			for (const image of scene.array || []) {
				++counts.outputs;
				if (image.render)
					++counts.render;
				if (image.reference)
					++counts.reference;
				if (image.difference)
					++counts.difference;
				if (normalizeStatus(image.status) === "missing-render")
					++counts.missingRender;
				if (normalizeStatus(image.status) === "missing-reference")
					++counts.missingReference;
			}
		}
		return counts;
	}

	function bundleStat(label, value, hint) {
		return el("div",{ className: "bundle-stat", dataset: { hint }, attrs: { tabindex: "0" } },el("span",{ text: label }),el("strong",{ text: value }));
	}

	function renderReportBundle() {
		clear(nodes.reportBundleCard);
		const counts = artifactCounts();
		const totalExr = counts.render + counts.reference + counts.difference;
		const sceneCount = (state.summary.results || []).length;
		append(nodes.reportBundleCard,
			el("h2",{ text: "Report Bundle" }),
			el("p",{ className: "ci-note", text: "Path tracer report payload.", dataset: { hint: HINTS.reportBundle }, attrs: { tabindex: "0" } }),
			el("div",{ className: "bundle-grid" },
				bundleStat("Scenes",String(sceneCount),"Rendered scene and sensor sessions recorded in this payload."),
				bundleStat("Outputs",String(counts.outputs),"Output records listed in summary.json."),
				bundleStat("EXR links",String(totalExr),"Renderable, reference and difference EXR links available in this payload."),
				bundleStat("Renders",String(counts.render),HINTS.renderArtifact),
				bundleStat("References",String(counts.reference),HINTS.referenceArtifact),
				bundleStat("Differences",String(counts.difference),HINTS.differenceArtifact),
				bundleStat("Missing renders",String(counts.missingRender),HINTS.missingRender),
				bundleStat("Missing refs",String(counts.missingReference),HINTS.missingReference)
			)
		);
	}

	function renderSummaryCard() {
		clear(nodes.summaryCard);
		nodes.summaryCard.appendChild(el("details",{ className: "inline-panel summary-json-panel" },
			el("summary",{ text: "Summary JSON" }),
			el("p",{ className: "summary-links" },el("a",{ href: summaryUrl(), text: "summary.json" })),
			el("pre",{ text: JSON.stringify(state.summary,null,2) })
		));
	}

	function renderCommitCard() {
		clear(nodes.commitCard);
		nodes.commitCard.appendChild(el("h2",{ text: "Commit" }));
		const commit = moduleCommit();
		if (!commit) {
			nodes.commitCard.appendChild(el("p",{ className: "ci-note", text: "Commit metadata is not available." }));
			return;
		}

		const hash = commit.commitHash || "";
		const shortHash = commit.commitShortHash || hash || "unknown";
		const hashUrl = hash ? "https://github.com/Devsh-Graphics-Programming/Nabla/commit/" + hash : "";
		const hashValue = hashUrl ? el("a",{ href: hashUrl, text: shortHash }) : shortHash;
		const meta = el("div",{ className: "commit-meta" },
			el("div",{ className: "stat" },hintLabel("Hash",HINTS.commitHash),el("strong",{ className: "commit-hash" },hashValue)),
			el("div",{ className: "stat" },hintLabel("Date",HINTS.commitDate),el("strong",{ text: commit.commitDate || "unknown" })),
			el("div",{ className: "stat" },hintLabel("Message",HINTS.commitMessage),el("div",{ className: "message-box", text: commitMessage(commit) }))
		);
		nodes.commitCard.appendChild(meta);
	}

	function renderMachineCard() {
		clear(nodes.machineCard);
		nodes.machineCard.appendChild(el("h2",{ text: "Machine" }));
		const machine = state.summary.machine || {};
		if (!Object.keys(machine).length) {
			nodes.machineCard.appendChild(el("p",{ className: "ci-note", text: "Machine metadata is not available." }));
			return;
		}

		const cpu = machine.cpu || {};
		const gpu = machine.gpu || {};
		const ram = machine.ram || {};
		const grid = el("div",{ className: "machine-grid" },
			runStat("Host",HINTS.machine,machine.hostname || "unknown"),
			runStat("OS",HINTS.machine,machine.os || "unknown"),
			runStat("CPU",HINTS.machine,cpu.description || "unknown"),
			runStat("Threads",HINTS.machine,String(cpu.logicalThreads || "unknown")),
			runStat("RAM",HINTS.machineMemory,formatBytes(ram.totalBytes)),
			runStat("GPU",HINTS.machineGpu,gpu.name || "unknown"),
			runStat("VRAM",HINTS.machineGpu,formatBytes(gpu.deviceLocalBytes)),
			runStat("Driver",HINTS.machineGpu,String(gpu.driverVersion || "unknown"))
		);
		nodes.machineCard.appendChild(grid);
	}

	function outputColumns(results) {
		const columns = [];
		const seen = new Set();
		for (const scene of results) {
			for (const image of scene.array || []) {
				if (seen.has(image.identifier))
					continue;
				seen.add(image.identifier);
				columns.push({ identifier: image.identifier, title: image.title || image.identifier });
			}
		}
		return columns;
	}

	function outputHint(identifier) {
		const value = String(identifier || "").toLowerCase();
		if (value === "tonemap")
			return HINTS.outputTonemap;
		if (value === "rwmc_cascades")
			return HINTS.outputRwmcCascades;
		if (value === "albedo")
			return HINTS.outputAlbedo;
		if (value === "normal")
			return HINTS.outputNormal;
		if (value === "denoised")
			return HINTS.outputDenoised;
		return "Path tracer output artifact.";
	}

	function fileStrip(image) {
		const strip = el("div",{ className: "file-strip" });
		let wrote = false;
		for (const [key,label] of [["render","Render"],["reference","Reference"],["difference","Difference"]]) {
			if (!image[key])
				continue;
			const hint = key === "render" ? HINTS.renderArtifact : key === "reference" ? HINTS.referenceArtifact : HINTS.differenceArtifact;
			wrote = true;
			strip.appendChild(el("a",{ href: artifactUrl(image[key]), text: label, dataset: { hint }, attrs: { download: artifactFilename(image[key]) } }));
		}
		if (!wrote)
			strip.appendChild(el("em",{ text: "none" }));
		return strip;
	}

	function previewButton(text, sceneIndex, outputIdentifier, variant = "render") {
		const button = el("button",{ className: "preview-btn", text, dataset: { hint: HINTS.previewButton } });
		button.type = "button";
		button.addEventListener("click",() => viewer.openPreview({
			sceneIndex,
			output: outputIdentifier,
			variant
		}));
		return button;
	}

	function sceneInfo(scene, sceneIndex) {
		const rawName = String(scene.display_name || scene.scene_name || scene.scene_path || "scene");
		const sensorMatch = rawName.match(/^(.*)_Sensor_([0-9]+)$/);
		const pathName = String(scene.scene_path || "").split(/[\\/]/).pop().replace(/\.[^.]*$/,"");
		let name = sensorMatch ? sensorMatch[1] : rawName;
		if (!name || name === "scene")
			name = pathName || name;
		return {
			index: scene.index || sceneIndex + 1,
			name,
			sensor: sensorMatch ? sensorMatch[2] : String(scene.sensor || 0)
		};
	}

	function imageCell(image, sceneIndex) {
		if (!image)
			return el("div",{ className: "output-summary missing-output", dataset: { hint: HINTS.missingOutput }, attrs: { tabindex: "0" } },
				badge("not-recorded"),
				el("div",{ className: "metric-main", text: "Output was not recorded" })
			);

		const cell = el("div",{ className: "output-summary" },badge(image.status));
		if (suppressComparisonMetric(image)) {
			const hint = normalizeStatus(image.status) === "missing-render" ? HINTS.missingRender :
				normalizeStatus(image.status) === "missing-reference" ? HINTS.missingReference : HINTS.missingOutput;
			cell.appendChild(hintable("metric-main",image.details || "No comparison data",hint));
		} else if (isSsimMetric(image)) {
			cell.appendChild(hintable("metric-main","Difference (SSIM)",HINTS.ssimMetric));
			cell.appendChild(hintable("metric-sub",ssimDifferenceText(image) + " / max " + String(image.ssim_error_threshold ?? "n/a"),HINTS.ssimMetric));
		} else if (Number(image.total_pixels || 0) > 0) {
			cell.appendChild(hintable("metric-main",String(image.error_pixels || 0) + " / " + String(image.allowed_error_pixels || 0) + " bad pixels",HINTS.badPixels));
			cell.appendChild(hintable("metric-sub",errorPercent(image) + ", max " + sci(image.max_abs_error),HINTS.errorMetric));
		} else {
			const hint = normalizeStatus(image.status) === "missing-render" ? HINTS.missingRender :
				normalizeStatus(image.status) === "missing-reference" ? HINTS.missingReference : HINTS.missingOutput;
			cell.appendChild(hintable("metric-main",image.details || "No comparison data",hint));
		}
		cell.appendChild(fileStrip(image));
		cell.appendChild(previewButton("Preview",sceneIndex,image.identifier));
		return cell;
	}

	function overviewFilterButton(label, value) {
		const button = el("button",{ className: "preview-btn" + (state.overviewFilter === value ? " is-active":""), text: label, dataset: { hint: HINTS.overviewFilter } });
		button.type = "button";
		button.addEventListener("click",() => {
			state.overviewFilter = value;
			renderOverview();
		});
		return button;
	}

	function expandFailedOnly() {
		const results = state.summary.results || [];
		for (const card of nodes.sceneDetails.querySelectorAll("details.scene-card")) {
			const sceneIndex = Number(card.dataset.sceneIndex || -1);
			const scene = results[sceneIndex];
			card.open = scene ? sceneHasProblem(scene) : false;
		}
	}

	function renderOverviewHeader() {
		const expandButton = el("button",{ className: "preview-btn", text: "Expand failed only", dataset: { hint: HINTS.expandFailedOnly } });
		expandButton.type = "button";
		expandButton.addEventListener("click",expandFailedOnly);
		return el("div",{ className: "card-header" },
			el("h2",{ text: "Scene Overview" }),
			el("div",{ className: "overview-actions" },
				overviewFilterButton("All","all"),
				overviewFilterButton("Failed only","failed"),
				expandButton
			)
		);
	}

	function renderOverview() {
		const allResults = state.summary.results || [];
		const sceneEntries = allResults
			.map((scene,sceneIndex) => ({ scene, sceneIndex }))
			.filter((entry) => state.overviewFilter !== "failed" || sceneHasProblem(entry.scene));
		clear(nodes.overviewCard);
		nodes.overviewCard.appendChild(renderOverviewHeader());
		if (!allResults.length) {
			nodes.overviewCard.appendChild(el("p",{ className: "ci-note", text: "No scenes were recorded in summary.json." }));
			return;
		}
		if (!sceneEntries.length) {
			nodes.overviewCard.appendChild(el("p",{ className: "ci-note", text: "No failing scenes in this report." }));
			return;
		}

		const columns = outputColumns(allResults);
		const table = el("table",{ className: "overview" });
		const headerRow = el("tr",{},el("th",{},hintLabel("Scene",HINTS.overviewScene)));
		for (const column of columns)
			headerRow.appendChild(el("th",{},hintLabel(column.title,outputHint(column.identifier))));
		headerRow.appendChild(el("th",{},hintLabel("Details",HINTS.overviewDetails)));
		table.appendChild(el("thead",{},headerRow));

		const body = el("tbody");
		sceneEntries.forEach(({ scene, sceneIndex }) => {
			const row = el("tr");
			const info = sceneInfo(scene,sceneIndex);
			const sceneStatus = effectiveSceneStatus(scene);
			const sceneCell = el("td",{ className: "scene side-cell" },
				el("div",{ className: "scene-summary" },
					badge(sceneStatus),
					el("div",{ className: "scene-copy" },
						el("div",{ className: "scene-index", text: "Scene " + String(info.index) }),
						el("div",{ className: "scene-title", text: info.name })
					),
					el("div",{ className: "metric", text: "Sensor " + info.sensor })
				)
			);
			row.appendChild(sceneCell);
			for (const column of columns) {
				const image = (scene.array || []).find((entry) => entry.identifier === column.identifier);
				row.appendChild(el("td",{ className: statusClass(image && image.status) + "-cell" },imageCell(image,sceneIndex)));
			}
			const firstImage = (scene.array || [])[0];
			const detailCell = el("td",{ className: "side-cell" },el("div",{ className: "detail-actions" }));
			if (firstImage)
				detailCell.firstChild.appendChild(previewButton("Preview EXR",sceneIndex,firstImage.identifier));
			const detailButton = el("button",{ className: "detail-link link-button", text: "Open details", dataset: { hint: HINTS.detailsButton } });
			detailButton.type = "button";
			detailButton.addEventListener("click",() => {
				const target = document.getElementById(sceneAnchor(scene,sceneIndex + 1));
				if (target)
					target.scrollIntoView({ behavior: "smooth", block: "start" });
			});
			detailCell.firstChild.appendChild(detailButton);
			row.appendChild(detailCell);
			body.appendChild(row);
		});
		table.appendChild(body);
		nodes.overviewCard.appendChild(el("div",{ className: "table-scroll" },table));
	}

	function fallbackCopy(text) {
		const textarea = document.createElement("textarea");
		textarea.value = text;
		textarea.setAttribute("readonly","");
		textarea.style.position = "fixed";
		textarea.style.insetInlineStart = "-100vw";
		document.body.appendChild(textarea);
		textarea.select();
		const copied = document.execCommand("copy");
		textarea.remove();
		if (!copied)
			throw new Error("copy failed");
	}

	async function copyText(text, button) {
		const originalText = button.textContent;
		try {
			if (navigator.clipboard && window.isSecureContext)
				await navigator.clipboard.writeText(text);
			else
				fallbackCopy(text);
			button.textContent = "Copied";
		} catch (_) {
			button.textContent = "Copy failed";
		}
		window.setTimeout(() => {
			button.textContent = originalText;
		},1400);
	}

	function copyPathButton(path) {
		const button = el("button",{ className: "copy-action", text: "Copy", dataset: { hint: HINTS.copyPath } });
		button.type = "button";
		button.addEventListener("click",() => copyText(path,button));
		return button;
	}

	function artifactAction(label, path, sceneIndex, outputIdentifier, variant) {
		const hint = variant === "render" ? HINTS.renderArtifact : variant === "reference" ? HINTS.referenceArtifact : HINTS.differenceArtifact;
		if (path)
			return el("span",{ className: "artifact-action" },
				el("a",{ className: "file-action", href: artifactUrl(path), text: label, dataset: { hint }, attrs: { download: artifactFilename(path) } }),
				copyPathButton(path),
				previewButton("Preview",sceneIndex,outputIdentifier,variant)
			);
		return el("span",{ className: "file-action is-disabled", text: label, dataset: { hint } });
	}

	function artifactLinks(image, sceneIndex) {
		return el("div",{ className: "artifact-links files-panel" },
			artifactAction("Download Render EXR",image.render,sceneIndex,image.identifier,"render"),
			artifactAction("Download Reference EXR",image.reference,sceneIndex,image.identifier,"reference"),
			artifactAction("Download Difference EXR",image.difference,sceneIndex,image.identifier,"difference")
		);
	}

	function renderDetails() {
		const results = state.summary.results || [];
		clear(nodes.sceneDetails);
		results.forEach((scene,sceneIndex) => {
			const sceneStatus = effectiveSceneStatus(scene);
			const open = results.length <= 3 || sceneStatus !== "passed";
			const card = el("details",{ className: "card scene-card", id: sceneAnchor(scene,sceneIndex + 1) });
			card.dataset.sceneIndex = String(sceneIndex);
			if (open)
				card.open = true;
			card.appendChild(el("summary",{ text: String(scene.index || sceneIndex + 1) + ". " + (scene.display_name || scene.scene_name || "scene") }));
			card.appendChild(el("div",{ className: "scene-status" },badge(sceneStatus)));
			const body = el("div",{ className: "scene-body" });
			body.appendChild(el("div",{ className: "kv scene-meta" },
				el("div",{},hintLabel("Scene path",HINTS.scenePath)),
				el("div",{ text: scene.scene_path || "" }),
				el("div",{},hintLabel("Sensor",HINTS.sensor)),
				el("div",{ text: String(scene.sensor || 0) })
			));
			if (scene.details)
				body.appendChild(el("p",{ className: "ci-note scene-note", text: scene.details }));

			const detailGrid = el("div",{ className: "detail-grid" },
				el("div",{ className: "detail-grid-head" },
					el("div",{ className: "detail-grid-cell", text: "Output" }),
					el("div",{ className: "detail-grid-cell", text: "Status" }),
					el("div",{ className: "detail-grid-cell", text: "Details" }),
					el("div",{ className: "detail-grid-cell", text: "Files" })
				)
			);
			for (const image of scene.array || []) {
				detailGrid.appendChild(el("div",{ className: "detail-grid-row" },
					el("div",{ className: "detail-grid-cell detail-output-cell" },el("div",{ className: "detail-cell-content" },hintable("output-name",image.title || image.identifier,outputHint(image.identifier)))),
					el("div",{ className: "detail-grid-cell detail-status-cell" },el("div",{ className: "detail-cell-content" },badge(image.status))),
					el("div",{ className: "detail-grid-cell detail-details-cell" },el("div",{ className: "detail-cell-content detail-message", text: image.details || "" })),
					el("div",{ className: "detail-grid-cell files-cell" },artifactLinks(image,sceneIndex))
				));
			}
			body.appendChild(el("div",{ className: "table-scroll detail-scroll" },detailGrid));
			card.appendChild(body);
			nodes.sceneDetails.appendChild(card);
		});
	}

	function buildPreviewManifest() {
		const scenes = [];
		(state.summary.results || []).forEach((scene,sceneIndex) => {
			const outputs = [];
			for (const image of scene.array || []) {
				const variants = [];
				if (image.render)
					variants.push({ identifier: "render", label: "Render", image: artifactUrl(image.render) });
				if (image.reference)
					variants.push({ identifier: "reference", label: "Reference", image: artifactUrl(image.reference) });
				if (image.difference)
					variants.push({ identifier: "difference", label: "Difference", image: artifactUrl(image.difference) });
				if (variants.length)
					outputs.push({
						identifier: image.identifier,
						title: image.title || image.identifier,
						status: image.status,
						variants
					});
			}
			if (outputs.length)
				scenes.push({
					index: sceneIndex,
					title: scene.display_name || scene.scene_name || "scene",
					sensor: scene.sensor || 0,
					outputs
				});
		});
		return { scenes };
	}

	function render() {
		nodes.loadError.hidden = true;
		renderHeaderStatus();
		renderPipelineNotice();
		renderRunCard();
		renderCommitCard();
		renderMachineCard();
		renderReportBundle();
		renderSummaryCard();
		renderOverview();
		renderDetails();
		viewer.setManifest(buildPreviewManifest());
	}

	function clearReportBody() {
		state.summary = null;
		state.dataBaseUrl = null;
		nodes.status.replaceChildren(badge("not-checked"));
		nodes.pipelineNotice.hidden = true;
		clear(nodes.pipelineNotice);
		clear(nodes.runCard);
		clear(nodes.commitCard);
		clear(nodes.reportBundleCard);
		clear(nodes.summaryCard);
		clear(nodes.overviewCard);
		clear(nodes.sceneDetails);
		viewer.setManifest({ scenes: [] });
	}

	function showLoadMessage(message) {
		clearReportBody();
		nodes.loadError.hidden = false;
		nodes.loadError.textContent = message;
	}

	async function openReport(reportPath, updateHash) {
		const normalized = normalizeReportPath(reportPath);
		state.reportPath = normalized;
		if (updateHash && normalized)
			setReportHash(normalized);

		const summary = await loadSummary(normalized);
		state.reportPath = normalized;
		state.summary = summary;
		state.dataBaseUrl = reportBaseUrl(normalized);
		render();
	}

	async function openRequestedReport() {
		try {
			await openReport(requestedReportPath(),false);
		} catch (error) {
			showLoadMessage(error && error.message ? error.message : String(error));
		}
	}

	function main() {
		window.addEventListener("hashchange",openRequestedReport);
		openRequestedReport();
	}

	main();
})();
